services:
  mysqldb_flag:
    container_name: mysqldb_flag
    image: mysql
    environment:
        MYSQL_DATABASE: flagsdb
        MYSQL_USER: cyberlabs
        MYSQL_PASSWORD: Fl4Gs_F0R_Fr33!!
        MYSQL_ROOT_PASSWORD: 1gn1s@r_0_0_t
    volumes:
            - ./flagdatabase/flag_db:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
            timeout: 20s
            retries: 10

  level_00:
    container_name: level_00
    build:
      context: level_00
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
        condition: service_healthy
    ports:
      - 10000:22

  level_01:
    container_name: level_01
    build:
      context: level_01
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10001:22
  
  level_02:
    container_name: level_02
    build:
      context: level_02
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10002:22
  
  level_03:
    container_name: level_03
    build:
      context: level_03
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10003:22

  level_04:
    container_name: level_04
    build:
      context: level_04
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10004:22

  level_05:
    container_name: level_05
    build:
      context: level_05
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10005:22

  level_06:
    container_name: level_06
    build:
      context: level_06
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10006:22

  level_07:
    container_name: level_07
    build:
      context: level_07
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10007:22 

  level_08:
    container_name: level_08
    build:
      context: level_08
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10008:22

  level_09:
    container_name: level_09
    build:
      context: level_09
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10009:22

  level_10:
    container_name: level_10
    build:
      context: level_10
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10010:22 

  level_11:
    container_name: level_11
    build:
      context: level_11
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10011:22

  level_12:
    container_name: level_12
    build:
      context: level_12
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10012:22

  level_13:
    container_name: level_13
    build:
      context: level_13
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10013:22 

  level_14:
    container_name: level_14
    build:
      context: level_14
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10014:22

  level_15:
    container_name: level_15
    build:
      context: level_15
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10015:22

  level_16:
    container_name: level_16
    build:
      context: level_16
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10016:22 

  level_17:
    container_name: level_17
    build:
      context: level_17
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10017:22

  level_18:
    container_name: level_18
    build:
      context: level_18
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10018:22

  level_19:
    container_name: level_19
    build:
      context: level_19
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10019:22 

  level_20:
    container_name: level_20
    build:
      context: level_20
      dockerfile: Dockerfile
    depends_on:
      mysqldb_flag:
          condition: service_healthy
    ports:
      - 10020:22
